services:
  # The main Indico container which runs flask
  # The same image is also used to run celery
  membership-api:
    container_name: membership-api
    image: stsatw/membership:latest
    command: /opt/membership/run.sh
    restart: unless-stopped
    environment:
      - REDIS_HOST=membership-redis
      - REDIS_PORT=6379
    ports:
     # The API is accessible directly via localhost:8084.
      - ${PORT:-8084}:80
    volumes:
      - ${OAUTH_CONFIG:-./client_secrets.json}:/opt/membership/client_secrets.json
  redis:
    container_name: membership-redis
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data

volumes:
  redis:
